### ISSUE TITLE
Use versioning

### ISSUE THREAD

**Issue by jszaszi** [QualityUnit/semanticwrap-php-client#2]
We are currently using the "dev-main" version of `semanticwrap-php-client` in LiveAgent composer. However, I would prefer the option to use a specific version (e.g. `"semanticwrap/semanticwrap-php-client": "^1.0.0"`) instead. This would allow our dependa-bot to notify us in LiveAgent about any new versions of `semanticwrap-php-client`.

This is not top prio issue and it's enough to do this change later, when semanticwrap API will be considered as stable.

**Comment by yasha-dev1** [comment]
Fixed
